spring:
  application:
    name: RoyaleAnalytics
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/royale_analytics
    type: com.zaxxer.hikari.HikariDataSource
    username: username
    password: password
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 15
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        show_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public